# Generated by Django 2.2.12 on 2021-05-21 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210521_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='signupDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 19, 22, 27, 284217)),
        ),
    ]
